import type { CatalogModule } from "./types";

const rfc3501: CatalogModule = {
	source: "RFC3501",
	extractionNote:
		"PHASE 0 SEED ONLY: sections 2.2.1, 2.2.2, 6.1.2, 6.2.1, 7.1.1, 7.1.4 and " +
		"7.1.5 partially extracted to exercise the suite machinery. Full extraction " +
		"of all client-binding requirements happens in Phase 1; ids here are stable " +
		"and will not be renumbered.",
	requirements: [
		{
			id: "RFC3501-2.2.1-1",
			source: "RFC3501",
			section: "2.2.1",
			title: "Client prefixes each command with a distinct tag",
			text:
				'Each client command is prefixed with an identifier (typically a short alphanumeric string, e.g., A0001, A0002, etc.) called a "tag". A different tag is generated by the client for each command.',
			level: "MUST",
			applicability: "always",
			profiles: ["rev1"],
			testability: "testable",
			notes: "Imperative prose without a 2119 keyword; treated as MUST.",
		},
		{
			id: "RFC3501-2.2.1-2",
			source: "RFC3501",
			section: "2.2.1",
			title: "Client follows command syntax strictly",
			text:
				"Clients MUST follow the syntax outlined in this specification strictly. It is a syntax error to send a command with missing or extraneous spaces or arguments.",
			level: "MUST",
			applicability: "always",
			profiles: ["rev1"],
			testability: "testable",
		},
		{
			id: "RFC3501-2.2.2-1",
			source: "RFC3501",
			section: "2.2.2",
			title: "Client accepts any server response at all times",
			text:
				"A client MUST be prepared to accept any server response at all times. This includes server data that was not requested.",
			level: "MUST",
			applicability: "always",
			profiles: ["rev1"],
			testability: "testable",
		},
		{
			id: "RFC3501-6.1.2-1",
			source: "RFC3501",
			section: "6.1.2",
			title: "NOOP usable as a periodic poll",
			text:
				"Since any command can return a status update as untagged data, the NOOP command can be used as a periodic poll for new messages or message status updates during a period of inactivity (this is the preferred method to do this).",
			level: "MAY",
			applicability: "conditional",
			profiles: ["rev1"],
			testability: "testable",
			notes:
				"Capability statement; tested as 'client offers a way to issue NOOP'. " +
				"Currently expected to fail as unimplemented (no public NOOP surface).",
		},
		{
			id: "RFC3501-6.2.1-1",
			source: "RFC3501",
			section: "6.2.1",
			title: "Client discards cached capabilities after STARTTLS",
			text:
				"Once [TLS] has been started, the client MUST discard cached information about server capabilities and SHOULD re-issue the CAPABILITY command.",
			level: "MUST",
			applicability: "conditional",
			profiles: ["rev1"],
			testability: "testable",
			notes: "MUST half of the sentence (discard cached capabilities).",
		},
		{
			id: "RFC3501-6.2.1-2",
			source: "RFC3501",
			section: "6.2.1",
			title: "Client re-issues CAPABILITY after STARTTLS",
			text:
				"Once [TLS] has been started, the client MUST discard cached information about server capabilities and SHOULD re-issue the CAPABILITY command.",
			level: "SHOULD",
			applicability: "conditional",
			profiles: ["rev1"],
			testability: "testable",
			notes: "SHOULD half of the sentence (re-issue CAPABILITY).",
		},
		{
			id: "RFC3501-6.2.1-3",
			source: "RFC3501",
			section: "6.2.1",
			title: "TLS negotiation begins immediately after the OK CRLF",
			text:
				"A [TLS] negotiation begins immediately after the CRLF at the end of the tagged OK response from the server.",
			level: "MUST",
			applicability: "conditional",
			profiles: ["rev1"],
			testability: "testable",
			notes:
				"Client-binding reading: no further plaintext octets may be sent after " +
				"the STARTTLS command until the handshake completes.",
		},
		{
			id: "RFC3501-7.1.1-1",
			source: "RFC3501",
			section: "7.1.1",
			title: "Client accepts the untagged OK greeting",
			text:
				"The untagged form indicates an information-only message; the nature of the information MAY be indicated by a response code. The untagged form is also used as one of three possible greetings at connection startup.",
			level: "MUST",
			applicability: "always",
			profiles: ["rev1"],
			testability: "testable",
			notes:
				"Implicit client obligation: accept all valid forms of the OK greeting " +
				"(with or without response codes) and proceed.",
		},
		{
			id: "RFC3501-7.1.4-1",
			source: "RFC3501",
			section: "7.1.4",
			title: "Client treats PREAUTH greeting as already authenticated",
			text:
				"The PREAUTH response is always untagged, and is one of three possible greetings at connection startup. It indicates that the connection has already been authenticated by external means; thus no LOGIN command is needed.",
			level: "MUST",
			applicability: "always",
			profiles: ["rev1"],
			testability: "testable",
			notes: "Imperative prose; client must enter authenticated state.",
		},
		{
			id: "RFC3501-7.1.5-1",
			source: "RFC3501",
			section: "7.1.5",
			title: "Client recognizes BYE greeting as connection rejection",
			text:
				"The BYE response is always untagged, and indicates that the server is about to close the connection. The BYE response is sent under one of four conditions: ... 4) as one of three possible greetings at connection startup, indicating that the server is not willing to accept a connection from this client. The server closes the connection immediately.",
			level: "MUST",
			applicability: "always",
			profiles: ["rev1"],
			testability: "testable",
			notes:
				"Elision ('...') covers conditions 1)-3) (logout, panic shutdown, " +
				"autologout); condition 4) is the connection-greeting rejection case. " +
				"All retained sentences are verbatim.",
		},
	],
};

export default rfc3501;
