import type { ComplianceReportData, SourceSummary } from "./aggregate";

function pct(score: number | null): string {
	// Fix 6: use Math.floor so 0.995 never rounds up to display as 100%.
	return score === null
		? "  n/a"
		: `${String(Math.floor(score * 100)).padStart(4)}%`;
}

/**
 * Fix 2: Escape a value for safe embedding in a Markdown table cell.
 * Collapses all whitespace runs to single spaces and escapes `|` as `\|`.
 */
function cell(value: string): string {
	return value.replace(/\s+/g, " ").replace(/\|/g, "\\|");
}

export function renderConsole(data: ComplianceReportData): string {
	const lines: string[] = [
		"",
		"IMAP CLIENT SPEC COMPLIANCE",
		"===========================",
	];
	const bySourceProfile = new Map<string, SourceSummary[]>();
	for (const s of data.summary) {
		const key = `${s.source} (${s.profile})`;
		const list = bySourceProfile.get(key) ?? [];
		list.push(s);
		bySourceProfile.set(key, list);
	}
	for (const [key, rows] of bySourceProfile) {
		lines.push("", key);
		for (const s of rows) {
			const c = s.counts;
			lines.push(
				`  ${s.level.padEnd(10)} ${pct(s.score)}  ` +
					`(pass ${c.pass}, violation ${c.violation}, unimplemented ${c.unimplemented}, ` +
					`untested ${c.untested}, untestable ${c.untestable})`,
			);
		}
	}
	if (data.problems.length) {
		lines.push("", "PROBLEMS:");
		for (const p of data.problems) lines.push(`  ! ${p}`);
	}
	lines.push("");
	return lines.join("\n");
}

export function renderMarkdown(data: ComplianceReportData): string {
	const lines: string[] = [
		"---",
		"title: IMAP Client Spec Compliance",
		"group: More Info",
		"order: 11",
		"---",
		"",
		"# IMAP Client Spec Compliance",
		"",
		"Compliance report generated by the compliance test suite. This report is a snapshot of the current state of the client library's compliance with the IMAP specification and related RFCs. To regenerate this report, run `npm run test:compliance`.",
		"",
		"## Summary",
		"",
		"| Source | Profile | Level | Score | Pass | Violation | Unimplemented | Untested | Untestable |",
		"|---|---|---|---|---|---|---|---|---|",
	];
	for (const s of data.summary) {
		const c = s.counts;
		lines.push(
			`| ${cell(s.source)} | ${cell(s.profile)} | ${cell(s.level)} | ${pct(s.score).trim()} | ` +
				`${c.pass} | ${c.violation} | ${c.unimplemented} | ${c.untested} | ${c.untestable} |`,
		);
	}
	lines.push("", "## Requirements", "");
	lines.push("| Requirement | Level | Profile | Status | Detail |");
	lines.push("|---|---|---|---|---|");
	for (const rr of data.requirements) {
		for (const [profile, pr] of Object.entries(rr.byProfile)) {
			let detail: string;
			if (pr.status === "fail") {
				const normalized = rr.req.text.replace(/\s+/g, " ");
				const truncated =
					normalized.length > 160
						? `${normalized.slice(0, 160)}…`
						: normalized;
				detail = cell(`${pr.failureKind}: ${truncated}`);
			} else if (pr.status === "untestable") {
				detail = cell(rr.req.untestableRationale ?? "");
			} else {
				detail = "";
			}
			lines.push(
				`| ${cell(`${rr.req.id} — ${rr.req.title}`)} | ${cell(rr.req.level)} | ${cell(profile)} | ${cell(pr.status)} | ${detail} |`,
			);
		}
	}
	if (data.problems.length) {
		lines.push("", "## Problems", "");
		for (const p of data.problems) lines.push(`- ${p}`);
	}
	lines.push("");
	return lines.join("\n");
}
