import type { ComplianceReportData, SourceSummary } from "./aggregate";

function pct(score: number | null): string {
	return score === null ? "  n/a" : `${(score * 100).toFixed(0).padStart(4)}%`;
}

export function renderConsole(data: ComplianceReportData): string {
	const lines: string[] = ["", "IMAP CLIENT SPEC COMPLIANCE", "==========================="];
	const bySourceProfile = new Map<string, SourceSummary[]>();
	for (const s of data.summary) {
		const key = `${s.source} (${s.profile})`;
		const list = bySourceProfile.get(key) ?? [];
		list.push(s);
		bySourceProfile.set(key, list);
	}
	for (const [key, rows] of bySourceProfile) {
		lines.push("", key);
		for (const s of rows) {
			const c = s.counts;
			lines.push(
				`  ${s.level.padEnd(10)} ${pct(s.score)}  ` +
					`(pass ${c.pass}, violation ${c.violation}, unimplemented ${c.unimplemented}, ` +
					`untested ${c.untested}, untestable ${c.untestable})`,
			);
		}
	}
	if (data.problems.length) {
		lines.push("", "PROBLEMS:");
		for (const p of data.problems) lines.push(`  ! ${p}`);
	}
	lines.push("");
	return lines.join("\n");
}

export function renderMarkdown(data: ComplianceReportData): string {
	const lines: string[] = [
		"# IMAP Client Spec Compliance",
		"",
		"Generated by the compliance suite reporter. Do not edit by hand.",
		"",
		"## Summary",
		"",
		"| Source | Profile | Level | Score | Pass | Violation | Unimplemented | Untested | Untestable |",
		"|---|---|---|---|---|---|---|---|---|",
	];
	for (const s of data.summary) {
		const c = s.counts;
		lines.push(
			`| ${s.source} | ${s.profile} | ${s.level} | ${pct(s.score).trim()} | ` +
				`${c.pass} | ${c.violation} | ${c.unimplemented} | ${c.untested} | ${c.untestable} |`,
		);
	}
	lines.push("", "## Requirements", "");
	lines.push("| Requirement | Level | Profile | Status | Detail |");
	lines.push("|---|---|---|---|---|");
	for (const rr of data.requirements) {
		for (const [profile, pr] of Object.entries(rr.byProfile)) {
			const detail =
				pr.status === "fail"
					? `${pr.failureKind}: ${rr.req.text.replace(/\s+/g, " ").slice(0, 160)}`
					: pr.status === "untestable"
						? (rr.req.untestableRationale ?? "")
						: "";
			lines.push(
				`| ${rr.req.id} — ${rr.req.title} | ${rr.req.level} | ${profile} | ${pr.status} | ${detail} |`,
			);
		}
	}
	if (data.problems.length) {
		lines.push("", "## Problems", "");
		for (const p of data.problems) lines.push(`- ${p}`);
	}
	lines.push("");
	return lines.join("\n");
}
