import type { SpecRequirement } from "../types";

export const note =
	"§2: sections 2.2.1 and 2.2.2 partially extracted (Phase 0 seed). " +
	"§3: no client-binding requirements. Full extraction in Phase 1.";

export const requirements: SpecRequirement[] = [
	{
		id: "RFC3501-2.2.1-1",
		source: "RFC3501",
		section: "2.2.1",
		title: "Client prefixes each command with a distinct tag",
		text:
			'Each client command is prefixed with an identifier (typically a short alphanumeric string, e.g., A0001, A0002, etc.) called a "tag". A different tag is generated by the client for each command.',
		level: "MUST",
		applicability: "always",
		profiles: ["rev1"],
		testability: "testable",
		notes: "Imperative prose without a 2119 keyword; treated as MUST.",
	},
	{
		id: "RFC3501-2.2.1-2",
		source: "RFC3501",
		section: "2.2.1",
		title: "Client follows command syntax strictly",
		text:
			"Clients MUST follow the syntax outlined in this specification strictly. It is a syntax error to send a command with missing or extraneous spaces or arguments.",
		level: "MUST",
		applicability: "always",
		profiles: ["rev1"],
		testability: "testable",
	},
	{
		id: "RFC3501-2.2.2-1",
		source: "RFC3501",
		section: "2.2.2",
		title: "Client accepts any server response at all times",
		text:
			"A client MUST be prepared to accept any server response at all times. This includes server data that was not requested.",
		level: "MUST",
		applicability: "always",
		profiles: ["rev1"],
		testability: "testable",
	},
];
